CREATE DATABASE productdb OWNER postgres TABLESPACE pg_default;

\c productdb;

CREATE TABLE products(
     id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     name   varchar(40) NOT NULL CHECK (name <> '')
);